### ISSUE TITLE
Merge OpenLayer wrapper packages into one

### ISSUE THREAD

**Issue by dandv** [MasterAM/meteor-ol3#1]
Would be nice to have only one OL package on Atmosphere, similar to the [Bootstrap-3 initiative](https://github.com/pinglamb/meteor-bootstrap3).

CC @mizzao, who authored https://atmospherejs.com/mizzao/openlayers

**Comment by mizzao** [comment]
I'm currently on OL 2.12.1 still. Probably fine to keep these separate for now.

**Comment by MasterAM** [comment]
Yes, completely different code-base and API.
Keeping this one and migrating to an easier to update scheme soon.
Sorry for the delay!
