### ISSUE TITLE
Use ol-debug.js?

### ISSUE THREAD

**Issue by foobarbecue** [MasterAM/meteor-ol3#3]
Hi, I'd like to debug my map in chrome dev tools, but the normal version of openlayers uses attribute and method names that aren't human-readable. Is there an easy way to make this package use ol-debug.js to get those human-readable names for debugging?

**Comment by MasterAM** [comment]
I considered that, but OpenLayers 3 uses the Closure library and compiler.
Hence, the debug version also outputs the `goog` symbol and potentially other symbols. In addition, I am not even sure that Meteor will be able to properly 'package' _ol3-debug.js_  for production.

I did not find an easy way around this. If it was possible, I would probably use the debug version in development mode only. However, such an approach may lead to compatibility or security issues, so I don't see MDG adopting it any time soon.

If you manage to find an elegant solution, let me know. I'd love to have the debug version as well.

**Comment by foobarbecue** [comment]
Yeah, seems like a bad idea to use ol-debug.js in production.

My solution for now is that I have a modified version of your package, with ol-debug.js in the ol3.fetch.js file, and I just keep that one installed on my local dev server and use yours in production. Not elegant, but it'll do for now.

I experimented with the [undocumented](https://github.com/meteor/meteor/issues/3843) debugOnly setting, but it's not really useful because there's no productionOnly setting and when I have both packages installed simultaneously, it's the ol.js version of the ol symbol that is available, not the debug one.

**Comment by MasterAM** [comment]
Actually, I thought that a local fork with debugOnly might work, if I could control the package load order.
I tried to create a branch with modified files that calls `api.use('alon:meteor-ol3')` in order to have the modified version loaded later, but got a namespace error, as `ol` was already used (see _ol-debug.js_@282).

**Comment by MasterAM** [comment]
Hmm, I added a file that unsets `ol` and it seems to do the trick.
You can try the [debug_version](https://github.com/MasterAM/meteor-ol3/tree/debug_version) branch.

**Comment by MasterAM** [comment]
I'm closing the, as the workaround appears to have done the trick.
If this is not working for you, please comment/reopen.
