### ISSUE TITLE
Include keyword "OpenLayers" on Atmosphere

### ISSUE THREAD

**Issue by gabrielalmeida** [MasterAM/meteor-ol3#4]
Hi,

Please update the package description to include the word `OpenLayers`, one can only find your package by searching specifically for `ol3`.

Thanks for this package!

**Comment by MasterAM** [comment]
Good idea! I'll update the description on the next release (should be out in a few days, according to their schedule).

**Comment by MasterAM** [comment]
Done.

**Comment by gabrielalmeida** [comment]
Great!

Thanks
